import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en" className="dark">
      <body className={inter.className}>
        <div 
        className="
        relative w-full flex justify-center items-center
        "
        >
        <Navbar/>
        </div>
        {children}</body>
    </html>
  );
}
// : Readonly<{
  // children: React.ReactNode;
// }>)
// this is the types in typescript toh firstly it is readonly mode and aur hum react ka react.node type accept kar rhe hai
// framework aur lib ke beech diff is framework bhot strict rules lagata hai that is why this is is framework har cheex me restrictions naming me bhi
